apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: grafana-bootstrap
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: grafana-bootstrap
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
    - secretKey: oidc-client-id
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_ID
    - secretKey: oidc-client-secret
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_SECRET
