apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infisical-tls
  namespace: infisical
spec:
  secretName: infisical-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - infisical.atlas.laucoin.fr
