apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: nightly-full
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    ttl: 720h
    includedNamespaces:
      - "*"
    defaultVolumesToFsBackup: true
