---
- name: Converge Atlas
  hosts: atlas
  become: true
  roles:
    - role: base
      tags: [base]
    - role: hardening
      tags: [hardening]
    - role: storage
      tags: [storage]
    - role: docker
      tags: [docker]
    - role: shell
      tags: [shell]
    - role: traefik
      tags: [traefik]
    - role: authelia
      tags: [authelia]
    - role: theme
      tags: [theme]
    - role: forgejo
      tags: [forgejo]
    - role: sonarqube
      tags: [sonarqube]
    - role: homeassistant
      tags: [homeassistant]
    - role: observability
      tags: [observability]
    - role: app
      tags: [app]
