---
- name: Converge Atlas
  hosts: atlas
  become: true
  roles:
    - role: base
      tags: [base]
    - role: hardening
      tags: [hardening]
    - role: storage
      tags: [storage]
    - role: docker
      tags: [docker]
    - role: shell
      tags: [shell]
