---
- name: Render the observability stack
  ansible.builtin.import_tasks: stack.yml

- name: Activate the observability service
  ansible.builtin.import_tasks: service.yml

- name: Integrate observability with traefik
  ansible.builtin.import_tasks: traefik.yml
